### Step 1: Import Required Libraries


In [51]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


### Step 2: Load and Prepare the Dataset

In [54]:
# Load data
data=pd.read_csv("C:/Users/sathi/Downloads/cleaned_data.csv")  

# Features and labels
X=data.drop("Outcome",axis=1)
y=data["Outcome"]
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

###  Step 4:Train-test split

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Step 3: Train the Model

In [73]:
X_train

array([[-0.54791859, -1.2379406 , -0.03198993, ..., -0.06562636,
        -0.50700636, -1.04154944],
       [ 1.53084665, -0.31744701,  0.79522451, ..., -0.61868436,
         2.44666971,  1.4259954 ],
       [-0.84488505,  0.57017181, -2.18274749, ..., -0.54591357,
         0.55003518, -0.95646168],
       ...,
       [ 1.82781311, -0.67906949,  1.12611029, ...,  1.91373908,
         2.00573238,  0.40494237],
       [-1.14185152,  0.63592135, -0.03198993, ...,  1.44800604,
        -0.8059981 , -0.36084741],
       [-1.14185152,  0.10992502,  1.95332473, ..., -1.44827135,
        -0.63385134, -1.04154944]])

In [69]:
# model=SVC(kernel='linear')
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n",classification_report(y_test, y_pred))


Accuracy: 0.7662337662337663
Confusion Matrix:
 [[83 16]
 [20 35]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.84      0.82        99
           1       0.69      0.64      0.66        55

    accuracy                           0.77       154
   macro avg       0.75      0.74      0.74       154
weighted avg       0.76      0.77      0.76       154



In [71]:
X_test

array([[ 0.63994726, -0.7776938 , -1.19009016, ...,  0.22545679,
        -0.1264714 ,  0.83038113],
       [-0.54791859, -0.31744701,  0.2161744 , ...,  0.47287747,
        -0.97814487, -1.04154944],
       [-0.54791859, -0.44894609, -0.69376149, ..., -0.24027626,
        -0.94794368, -1.04154944],
       ...,
       [ 1.23388019, -0.87631812, -0.03198993, ...,  0.6329732 ,
         0.03963513,  2.02160968],
       [-0.54791859,  0.80029521, -0.19743282, ..., -0.64779267,
        -0.40734244, -0.36084741],
       [ 1.23388019, -1.56668831, -0.19743282, ...,  0.41466084,
         0.70406123,  0.49003012]])

### Save to model on PKL file

In [17]:
import pickle

# Save model and scaler
pickle.dump(model, open("diabetes_model.pkl", "wb"))
pickle.dump(scaler, open("scaler.pkl", "wb"))
